name: 'binary_evaluation'

config-version: 2
version: '0.1'

profile: 'bigquery_profile'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.8.0-b3", "<2.0.0"]

models:
  use_anonymous_sproc: True
